captcha/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('captcha.views',
    url(r'image/(?P<key>\w+)/$', 'captcha_image', name='captcha-image', kwargs={'scale': 1}),
    url(r'image/(?P<key>\w+)@2/$', 'captcha_image', name='captcha-image-2x', kwargs={'scale': 2}),
    url(r'audio/(?P<key>\w+)/$', 'captcha_audio', name='captcha-audio'),
    url(r'refresh/$', 'captcha_refresh', name='captcha-refresh'),
)

drummersaransk/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('drummersaransk',
	url(r'^accounts/logout/$', 'views.logout', name='logout', ),	
	url(r'^accounts/login/$', 'views.login', name='login', ),
	url(r'^accounts/loggedin/$', 'views.loggedin', ),
	url(r'^accounts/invalid_login/$', 'views.invalid_login', ),
	
	url(r'^accounts/registration/$', 'views.registration', name='registration', ),
	url(r'^accounts/registration_success/$', 'views.registration_success', ),		
	
	url(r'^userprofile/friends_search/$', 'views.friends_search', name='friends_search', ),
	
	url(r'^userprofile/friends_list_edit/$', 'views.friends_list_edit', name='friends_list_edit', ),
	url(r'^userprofile/friends_list_edit/(?P<friend_id>[0-9]*)/$', 'views.friends_list_edit', name='friends_list_edit', ),
			
	url(r'^userprofile/password_page/$', 'views.password_page', name='password_page', ),		
	url(r'^userprofile/password_page_changed/$', 'views.password_page_changed', ),	
		
	url(r'^userprofile/avatar_page/$', 'views.avatar_page', name='avatar_page', ),		
	url(r'^userprofile/avatar_page_changed/$', 'views.avatar_page_changed', ),	
		
	url(r'^userprofile/personal_data_page/$', 'views.personal_data_page', name='personal_data_page', ),		
	url(r'^userprofile/personal_data_page_changed/$', 'views.personal_data_page_changed', ),
	
	url(r'^userprofile/drum_data_page/$', 'views.drum_data_page', name='drum_data_page', ),		
	url(r'^userprofile/drum_data_page_changed/$', 'views.drum_data_page_changed', name='drum_data_page_changed', ),	
			
	url(r'^userprofile/path_glory_edit/$', 'views.path_glory_edit', name='path_glory_edit', ),		
	url(r'^userprofile/path_glory_add_item/$', 'views.path_glory_add_item', name='path_glory_add_item', ),		
	url(r'^userprofile/path_glory_edit/(?P<id>[0-9]+)/$', 'views.path_glory_edit_item', name='path_glory_edit_item', ),		
	url(r'^userprofile/path_glory_edit_item_changed/$', 'views.path_glory_edit_item_changed', name='path_glory_edit_item_changed', ),		
	url(r'^userprofile/path_glory_add_item_added/$', 'views.path_glory_add_item_added', name='path_glory_add_item_added', ),		
						
	url(r'^(?P<id>[0-9]+)/$', 'views.user_personal', name='user_personal', ),
	url(r'^(?P<id>[0-9]+)/druminfo/$', 'views.user_druminfo', name='user_druminfo', ),
	url(r'^(?P<id>[0-9]+)/path_glory/$', 'views.path_glory', name='path_glory', ),	
	url(r'^(?P<id>[0-9]+)/path_glory/(?P<id_p>[0-9]+)/$', 'views.user_path_glory_page', name='user_path_glory_page', ),
	url(r'^(?P<id>[0-9]+)/friends_list/$', 'views.user_friends_list', name='user_friends_list', ),
	
	url(r'^captcha/', include('captcha.urls')),
	url(r'^admin/', include(admin.site.urls)),	
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )


urlpatterns += patterns('drummersaransk',
	url(r'^$', 'views.index', ),
	url(r'^index/', 'views.login', ),
	url(r'^page_error404/', 'views.page_error404', ),
	url(r'^None/', 'views.login', ),	
	url(r'^.*/', 'views.page_error404', ),
)
   
   
if settings.DEBUG:
	import debug_toolbar
	urlpatterns += patterns('',
		url(r'^__debug__/', include(debug_toolbar.urls)),
	)   

drummersaransk/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager
from django.conf import settings
import os

from captcha.fields import CaptchaField


class Status(models.Model):		
	status = models.CharField(
		max_length=40, 
		blank=False,
	)		
		
	@classmethod
	def get_status_list(self):
		status_list = list()
		status_list.append(('', 'Не указан'))
		
		for values_ins in Status.objects.all().values_list('id', 'status'):
			status_list.append(values_ins)
			
		return status_list				
		
		
class Gender(models.Model):		
	gender = models.CharField(
		max_length=10, 
		blank=False,
	)	
		
	@classmethod
	def get_gender_list(self):
		gender_list = list()
		gender_list.append(('', 'Не указан'))
		
		for values_ins in Gender.objects.all().values_list('id', 'gender'):
			gender_list.append(values_ins)
			
		return gender_list		
		
		
class Teacher(models.Model):		
	teacher = models.CharField(
		max_length=40, 
		blank=False,
	)	

	def __str__(self):
		return self.teacher
				

class UserProfile(User):			
	family = models.CharField(
		'Фамилия',
		max_length=30, 
		blank=True,
		null=True,
	)
	name1 = models.CharField(
		'Имя',
		max_length=30, 
		blank=True,
		null=True,
	)
	name2 = models.CharField(
		'Отчество',
		max_length=30, 
		blank=True,
		null=True,
	)
	nickname = models.CharField(
		'Отображаемое имя',
		max_length=30, 
		blank=False,
	)
	gender = models.ForeignKey(
		Gender,
		verbose_name='Пол',
		blank=True,
		null=True,
	)
	birth_date = models.DateField(
		'Дата рождения',
		blank=True,
		null=True,
	)
	status = models.ForeignKey(
		Status,
		verbose_name='Статус',
		blank=True,
		null=True,
	)
	city = models.CharField(
		'Город',
		max_length=50, 
		default='Саранск', 
		blank=False,
	)
	phone = models.CharField(
		'Номер телефона',
		max_length=50, 
		blank=True,
		null=True,
	)
	skype = models.CharField(
		'Skype',
		max_length=50, 
		blank=True,
		null=True,
	)
	email_address = models.EmailField(
		'Адрес электронной почты',
		max_length=50, 
		blank=False,
	)	
	other = models.TextField(
		'Интересы и увлечения',
		max_length=500,
		blank=True,
		null=True,
	)
	avatar = models.ImageField(
		'Фото',
		upload_to='userprofile/avatar/', 
		blank=True,
		null=True,
	)

	drum_period_1 = models.DateField(
		'Начал играть',
		blank=True,
		null=True,
	)	
	drum_period_2 = models.DateField(
		'Закончил играть',
		blank=True,
		null=True,
	)	
	drum_photo = models.ImageField(
		'Фото инструмента',
		upload_to='userprofile/drum_photo/', 
		blank=True,
		null=True,
	)
	drums = models.CharField(
		'Использую барабаны',
		max_length=300, 
		blank=True,
		null=True,
	)	
	cymbals = models.CharField(
		'Использую тарелки',
		max_length=300, 
		blank=True,
		null=True,
	)	
	hardware = models.CharField(
		'Использую хардвер',
		max_length=300, 
		blank=True,
		null=True,
	)	
	sticks = models.CharField(
		'Использую палочки',
		max_length=300, 
		blank=True,
		null=True,
	)	
	plastics = models.CharField(
		'Использую пластики',
		max_length=300, 
		blank=True,
		null=True,
	)	
	groups_past = models.CharField(
		'Играл в группах',
		max_length=300, 
		blank=True,
		null=True,
		help_text='перечислить через запятую',
	)
	groups_present = models.CharField(
		'Играю в группах',
		max_length=300, 
		blank=True,
		null=True,
		help_text='перечислить через запятую',
	)		
	teacher = models.ForeignKey(
		Teacher,
		verbose_name='Преподаватель',
		blank=True,
		null=True,
	)	
	teacher_fio = models.CharField(
		'Ф. И. О. преподователя',
		max_length=300, 
		blank=True,
		null=True,
	)
	drummers = models.CharField(
		'Уважаемые барабанщики',
		max_length=300, 
		blank=True,
		null=True,
		help_text='перечислить через запятую',
	)		
		
	objects = UserManager()
		
	@classmethod
	def get_city_list(self):
		result = self.objects.values_list('city', flat=True).distinct()	
		return result
		
	@classmethod
	def get_distinct_cities(self):		
		cities_list = list()
		cities_list.append(('', 'Не указан'))
		
		for values_ins in UserProfile.objects.all().values_list('city', 'city').distinct():
			cities_list.append(values_ins)
			
		return cities_list						


class PathGlory(models.Model):
	user_id = models.IntegerField(
		'',
	)		
	title = models.CharField(
		'Название события',
		max_length=100, 
		blank=False,
	)			
	date = models.DateField(
		'Дата проведения',
		blank=True,
		null=True,
	)		
	place = models.CharField(
		'Место проведения',
		max_length=200, 
		blank=True,
		null=True,
	)		
	teaser = models.TextField(
		'Вступительный текст (тизер)',
		max_length=10000, 
		blank=False,
		help_text='Будет отображаться в ленте',
	)			
	text = models.TextField(
		'Основной текст',
		max_length=100, 
		blank=False,
		help_text='Будет отображаться на отдельной странице',
	)			
	path_glory_photo = models.ImageField(
		'Фото',
		blank=True,
		upload_to='userprofile/path_glory_photo/', 
		null=True,
	)							
	
	@classmethod
	def get_all_entries(self):
		return self.objects.all()
		
	@classmethod
	def get_all_user_entries(self, id):
		return self.objects.filter(user_id=id)		
		
	@classmethod
	def get_entry(self, user_id, id_p):
		return self.objects.get(id=id_p, user_id=user_id)	
		
	@classmethod
	def get_entry_short(self, id):
		return self.objects.get(id=id)				


class Friends(models.Model):		
	user_id = models.IntegerField(
		blank=False,
		null=False,
	)	
	friend_id = models.IntegerField(
		blank=False,
		null=False,	
	)	
	
	@classmethod
	def get_entry(self, user_id, friend_id):
		try:
			self.objects.get(user_id=user_id, friend_id=friend_id)
		except:
			return False
		else:
			return True
		
	@classmethod
	def set_entry(self, user_id, friend_id):
		try:
			obj = self.objects.create(
				user_id = user_id,
				friend_id = friend_id,
			)			
			obj.save
		except:
			return False
		else:
			return True
		
	@classmethod
	def del_entry(self, user_id, friend_id):	
		try:
			self.objects.get(user_id=user_id, friend_id=friend_id).delete()
		except:
			return False
		else:
			return True		
			
	@classmethod
	def get_all_entries(self, user_id):
		return self.objects.filter(user_id=user_id)
		
	@classmethod
	def count_entry(self, user_id):		
		return self.objects.filter(user_id=user_id).count()
		
	@classmethod
	def exists_entry(self, user_id):		
		res = self.objects.filter(user_id=user_id)
		return res

drummersaransk/templates/userprofile/avatar_page.html
{% extends "page_base.html" %}{% load thumbnail %}{% block title %} - Загрузка аватара{% endblock %}{% block content %}	<section class="section avatar_page edit_data">		<h2 class="h2">Загрузка аватара</h2>					<form class="avatar_form common_form" action="{% url 'avatar_page' %}" method="POST" enctype="multipart/form-data">			{% csrf_token %}						{% if avatar %}				{% thumbnail avatar "230x230" crop="center" as im %}					<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">				{% endthumbnail %}							{% endif %}									<div class="cell">				<label class="label">{# {{ form.avatar.label }} #}</label>								{# {{ form.avatar }} #}				<input id="id_avatar" name="avatar" type="file" value="23" />								{{ form.avatar.errors }}			</div>									<div class="cell">				<input class="submit btn btn-info" type="submit" value="Изменить" />			</div>		</form>	</section>{% endblock %}

drummersaransk/templates/userprofile/avatar_page_changed.html
{% extends "page_base.html" %}{% block title %} - Аватар загружен{% endblock %}{% block content %}	<section class="section avatar_page_changed">		<h2 class="h2">Аватар загружен</h2>	</section>{% endblock %}

drummersaransk/templates/userprofile/drum_data_page_changed.html
{% extends "page_base.html" %}{% block title %} - Изменения сохранены{% endblock %}{% block content %}	<section class="section personal_data_changed">		<h2 class="h2">Изменения сохранены</h2>	</section>{% endblock %}

drummersaransk/templates/userprofile/friends_list_edit.html
{% extends "page_base.html" %}{% load thumbnail tags_drummersaransk %}{% block title %} - Редактирование списка друзей{% endblock %}{% block content %}	<section class="section friends_list_page">		<h2 class="h2">Редактирование списка друзей</h2>		<div class="friends_body">			{% if count_friends > 0 %}				{% for entry in all_entries %}					{% friend_item entry.friend_id flag_buttons_visibility %}				{% endfor %}			{% else %}				Друзей пока нет.			{% endif %}		</div>	</section>{% endblock %}

drummersaransk/templates/userprofile/password_page.html
{% extends "page_base.html" %}{% block title %} - Изменить пароль{% endblock %}{% block content %}	<section class="section password_page edit_data">		<h2 class="h2">Изменить пароль</h2>				<form class="password_form common_form" action="{% url 'password_page' %}" method="POST">			{% csrf_token %}						<div class="cell">				<label class="label">{{ form.password_old.label }}</label>								{{ form.password_old }}								{{ form.password_old.errors }}			</div>			<div class="cell">				<label class="label">{{ form.password1.label }}</label>								{{ form.password1 }}								{{ form.password1.errors }}			</div>			<div class="cell">				<label class="label">{{ form.password2.label }}</label>								{{ form.password2 }}								{{ form.password2.errors }}								{{ form.non_field_errors }}			</div>							<div class="cell">				<input class="submit btn btn-info" type="submit" value="Изменить" />			</div>		</form>	</section>{% endblock %}

drummersaransk/templates/userprofile/password_page_changed.html
{% extends "page_base.html" %}{% block title %} - Пароль изменён{% endblock %}{% block content %}	<section class="section password_page_changed">		<h2>Пароль изменён</h2>	</section>{% endblock %}

drummersaransk/templates/userprofile/personal_data_page_changed.html
{% extends "page_base.html" %}{% block title %} - Изменения сохранены{% endblock %}{% block content %}	<section class="section personal_data_changed">		<h2 class="h2">Изменения сохранены</h2>	</section>{% endblock %}